broodjes2\TeLaet\Entities\Postcode:
  type: entity
  repositoryClass: broodjes2\TeLaet\Repository\PostcodeRepository
  table: postcode

  id:
    id:
      type: integer
      generator:
        strategy: AUTO
        
  indexes:
    postcode_idx:
      columns: [ postcode ]

  oneToMany:
    users:
      targetEntity: User
      mappedBy: postcode

  fields:
    postcode:
      type: string
      length: 4
      nullable: false
    town:
      type: string
      length: 100